---
  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Start NGiNX
    service:
      name: nginx
      state: started
      enabled: yes

  - debug: var=ansible_eth0.ipv4.address
